version = 0.1
[default.deploy.parameters]
stack_name = "decap-oauth-proxy"
resolve_s3 = true
s3_prefix = "decap-oauth-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
